// Hybrid dispersive: decomposition, bar SWE, pack/unpack, spectrum ops, transport, merge.
#import bevy_fft::bindings::{
    buffer_a_re,
    buffer_a_im,
    buffer_b_re,
    buffer_c_re,
    buffer_c_im,
}

struct DispersiveSim {
    n: u32,
    diffusion_iters: u32,
    g: f32,
    dt: f32,
    dx: f32,
    tile_world: f32,
    gamma_surf: f32,
    d_grad_penalty: f32,
    timestamp: u32,
    spectral_flags: u32,
    h_bar_omega: f32,
    spectral_fixed_depth: f32,
    airy_depth_0: f32,
    airy_depth_1: f32,
    airy_depth_2: f32,
    airy_depth_3: f32,
    airy_stack_channel: u32,
    h_avgmax_beta: f32,
    vel_clamp_alpha: f32,
    brush_on: u32,
    brush_radius: f32,
    brush_strength: f32,
    pointer_x: f32,
    pointer_y: f32,
    pointer_ox: f32,
    pointer_oy: f32,
    _pad0: f32,
    _pad1: f32,
}

const SPECTRAL_FIXED_DEPTH: u32 = 1u;

@group(1) @binding(0) var<uniform> sim: DispersiveSim;
@group(1) @binding(1) var d_state: texture_storage_2d<rgba32float, read_write>;
@group(1) @binding(2) var d_bar: texture_storage_2d<rgba32float, read_write>;
@group(1) @binding(3) var d_tilde: texture_storage_2d<rgba32float, read_write>;
@group(1) @binding(4) var d_bed: texture_storage_2d<rgba32float, read_write>;
@group(1) @binding(5) var d_scratch: texture_storage_2d<rgba32float, read_write>;
@group(1) @binding(6) var d_hspec_re: texture_storage_2d<rgba32float, read_write>;
@group(1) @binding(7) var d_hspec_im: texture_storage_2d<rgba32float, read_write>;
@group(1) @binding(8) var d_qspec_backup: texture_storage_2d<rgba32float, read_write>;
@group(1) @binding(9) var d_airy_stack_qx: texture_storage_2d<rgba32float, read_write>;
@group(1) @binding(10) var d_airy_stack_qy: texture_storage_2d<rgba32float, read_write>;
@group(1) @binding(11) var bar_face_u: texture_storage_2d<r32float, read_write>;
@group(1) @binding(12) var bar_face_w: texture_storage_2d<r32float, read_write>;
@group(1) @binding(13) var bar_mac_u: texture_storage_2d<rgba32float, read_write>;
@group(1) @binding(14) var bar_mac_w: texture_storage_2d<rgba32float, read_write>;
/// Previous-step cell-centered bulk velocity (`.rg` = ū) for Alg. 3 midpoint.
@group(1) @binding(15) var bar_vel_prev: texture_storage_2d<rgba32float, read_write>;

const PI: f32 = 3.1415926535;

fn clampi(i: i32, n: i32) -> i32 { return clamp(i, 0, n - 1i); }

/// Periodic wrap. Airy uses a periodic FFT, so spatial neighbor stencils in the hybrid
/// merge/transport path must wrap too. Edge clamp fights the spectrum and seeds lattices.
fn wrapi(i: i32, n: i32) -> i32 {
    let m = i % n;
    return select(m + n, m, m >= 0);
}

fn is_finite_f(x: f32) -> bool {
    // NaN != NaN; reject huge non-finite magnitudes without relying on isFinite().
    return (x == x) && (abs(x) < 1e20);
}

fn b_at(ix: i32, iy: i32) -> f32 {
    let n1 = i32(sim.n);
    return textureLoad(d_bed, vec2u(u32(wrapi(ix, n1)), u32(wrapi(iy, n1)))).r;
}

fn s_at(ix: i32, iy: i32) -> vec4f {
    let n1 = i32(sim.n);
    return textureLoad(d_state, vec2u(u32(wrapi(ix, n1)), u32(wrapi(iy, n1))));
}

fn bar_at(ix: i32, iy: i32) -> vec4f {
    let n1 = i32(sim.n);
    return textureLoad(d_bar, vec2u(u32(wrapi(ix, n1)), u32(wrapi(iy, n1))));
}

fn tilde_at(ix: i32, iy: i32) -> vec4f {
    let n1 = i32(sim.n);
    return textureLoad(d_tilde, vec2u(u32(wrapi(ix, n1)), u32(wrapi(iy, n1))));
}

fn clamp_q_cell(h: f32, qx: f32, qy: f32) -> vec2f {
    let qm = max(h, 0.0) * sim.dx / (4.0 * max(sim.dt, 1e-6));
    let nq = length(vec2f(qx, qy));
    if (nq > qm && nq > 1e-12) {
        let sc = qm / nq;
        return vec2f(qx * sc, qy * sc);
    }
    return vec2f(qx, qy);
}

@compute @workgroup_size(16, 16, 1)
fn decompose_init(@builtin(global_invocation_id) id: vec3u) {
    let n = sim.n;
    if (id.x >= n || id.y >= n) { return; }
    let ix = i32(id.x);
    let iy = i32(id.y);
    let b = b_at(ix, iy);
    let s = textureLoad(d_state, id.xy);
    let hw = max(s.r, 0.0);
    let eta = b + hw;
    // Free-surface only. Momentum stays in the bar; surface q̃ is regenerated by Airy.
    textureStore(d_scratch, id.xy, vec4(eta, 0.0, 0.0, 0.0));
}

fn grad_h2(ix: i32, iy: i32) -> f32 {
    let hl = max(s_at(ix - 1, iy).r, 0.0);
    let hr = max(s_at(ix + 1, iy).r, 0.0);
    let hd = max(s_at(ix, iy - 1).r, 0.0);
    let hu = max(s_at(ix, iy + 1).r, 0.0);
    let gx = (hr - hl) / (2.0 * sim.dx);
    let gy = (hu - hd) / (2.0 * sim.dx);
    return gx * gx + gy * gy;
}

@compute @workgroup_size(16, 16, 1)
fn diffuse_eta_step(@builtin(global_invocation_id) id: vec3u) {
    let n = sim.n;
    if (id.x >= n || id.y >= n) { return; }
    let ix = i32(id.x);
    let iy = i32(id.y);
    let n1 = i32(n);
    let h_c = max(s_at(ix, iy).r, 1e-3);
    let d_pen = sim.d_grad_penalty;
    let ax = (h_c * h_c / 64.0) * exp(-d_pen * grad_h2(ix, iy));
    let dx = sim.dx;
    // Explicit FTCS needs dT ≤ dx² / (4 α). A fixed dT=0.25 is only safe near paper-scale
    // dx≈1 m; with finer grids it NaNs the field on the first step.
    let dT_max = 0.24 * dx * dx / max(4.0 * ax, 1e-8);
    let dT = min(0.25, dT_max);
    let Hc = textureLoad(d_scratch, id.xy).r;
    let Hl = textureLoad(d_scratch, vec2u(u32(wrapi(ix - 1, n1)), u32(iy))).r;
    let Hr = textureLoad(d_scratch, vec2u(u32(wrapi(ix + 1, n1)), u32(iy))).r;
    let Hd = textureLoad(d_scratch, vec2u(u32(ix), u32(wrapi(iy - 1, n1)))).r;
    let Hu = textureLoad(d_scratch, vec2u(u32(ix), u32(wrapi(iy + 1, n1)))).r;
    let lap = (Hl + Hr + Hd + Hu - 4.0 * Hc) / (dx * dx);
    var H_new = Hc + ax * lap * dT;
    if (!is_finite_f(H_new)) {
        H_new = Hc;
    }
    textureStore(d_scratch, id.xy, vec4(H_new, 0.0, 0.0, 0.0));
}

@compute @workgroup_size(16, 16, 1)
fn decompose_split(@builtin(global_invocation_id) id: vec3u) {
    let n = sim.n;
    if (id.x >= n || id.y >= n) { return; }
    let ix = i32(id.x);
    let iy = i32(id.y);
    let b = b_at(ix, iy);
    let filt = textureLoad(d_scratch, id.xy);
    let h_bar = max(filt.r - b, 0.0);
    let s = s_at(ix, iy);
    let hw = max(s.r, 0.0);
    let h_t = hw - h_bar;
    // All momentum stays in the bar. Surface q̃ comes from the dispersive step.
    // Keep previous pre-Airy h̃ in `.a` for Alg. 2 time un-stagger average.
    let prev_h = textureLoad(d_tilde, id.xy).a;
    let qxb = s.g;
    let qyb = s.b;
    textureStore(d_bar, id.xy, vec4(h_bar, qxb, qyb, 0.0));
    textureStore(d_tilde, id.xy, vec4(h_t, 0.0, 0.0, prev_h));
}

// --- Bulk bar: Chentanez–Müller 2010 (CMF10), same order as `shallow_water/simulator.wgsl` MacCormack + upwind h + η pressure.

fn bar_nxi() -> i32 { return i32(sim.n); }

fn bar_h_at(ic: i32, jc: i32) -> f32 {
    // Periodic like Airy/FFT. Clamp-to-edge here was seeding border lattices into the bulk SWE.
    let n1 = bar_nxi();
    let c = vec2u(u32(wrapi(ic, n1)), u32(wrapi(jc, n1)));
    return max(textureLoad(d_bar, c).r, 0.0);
}

fn bar_eta_at(ic: i32, jc: i32) -> f32 {
    return b_at(ic, jc) + bar_h_at(ic, jc);
}

fn bar_u_face_ij(fi: i32, jc: i32) -> vec2u {
    let n1 = bar_nxi();
    // Period n: face n stores the same seam as face 0 after sync; wrap reads onto 0..n-1.
    return vec2u(u32(wrapi(fi, n1)), u32(wrapi(jc, n1)));
}

fn bar_w_face_ij(ic: i32, fj: i32) -> vec2u {
    let n1 = bar_nxi();
    return vec2u(u32(wrapi(ic, n1)), u32(wrapi(fj, n1)));
}

fn bar_u_face_read(fi: i32, jc: i32) -> f32 {
    return textureLoad(bar_face_u, bar_u_face_ij(fi, jc)).x;
}

fn bar_w_face_read(ic: i32, fj: i32) -> f32 {
    return textureLoad(bar_face_w, bar_w_face_ij(ic, fj)).x;
}

fn bar_u_mac0_at(fi: i32, jc: i32) -> f32 {
    return textureLoad(bar_mac_u, bar_u_face_ij(fi, jc)).x;
}

fn bar_w_mac0_at(ic: i32, fj: i32) -> f32 {
    return textureLoad(bar_mac_w, bar_w_face_ij(ic, fj)).x;
}

fn bar_sample_u_bilinear(x: f32, y: f32) -> f32 {
    let nyi = bar_nxi();
    let nxf = bar_nxi() + 1;
    let jf = y - 0.5;
    var j0 = i32(floor(jf));
    let ty = jf - f32(j0);
    j0 = clamp(j0, 0, nyi - 1);
    let j1 = min(j0 + 1, nyi - 1);
    var i0 = i32(floor(x));
    let tx = x - f32(i0);
    i0 = clamp(i0, 0, nxf - 2);
    let i1 = min(i0 + 1, nxf - 1);
    let u00 = bar_u_face_read(i0, j0);
    let u10 = bar_u_face_read(i1, j0);
    let u01 = bar_u_face_read(i0, j1);
    let u11 = bar_u_face_read(i1, j1);
    return mix(mix(u00, u10, tx), mix(u01, u11, tx), ty);
}

fn bar_sample_u_bilinear_mac0(x: f32, y: f32) -> f32 {
    let nyi = bar_nxi();
    let nxf = bar_nxi() + 1;
    let jf = y - 0.5;
    var j0 = i32(floor(jf));
    let ty = jf - f32(j0);
    j0 = clamp(j0, 0, nyi - 1);
    let j1 = min(j0 + 1, nyi - 1);
    var i0 = i32(floor(x));
    let tx = x - f32(i0);
    i0 = clamp(i0, 0, nxf - 2);
    let i1 = min(i0 + 1, nxf - 1);
    let u00 = bar_u_mac0_at(i0, j0);
    let u10 = bar_u_mac0_at(i1, j0);
    let u01 = bar_u_mac0_at(i0, j1);
    let u11 = bar_u_mac0_at(i1, j1);
    return mix(mix(u00, u10, tx), mix(u01, u11, tx), ty);
}

fn bar_sample_w_bilinear(x: f32, y: f32) -> f32 {
    let nxi = bar_nxi();
    let nyf = bar_nxi() + 1;
    let ifloat = x - 0.5;
    var i0 = i32(floor(ifloat));
    let tx = ifloat - f32(i0);
    i0 = clamp(i0, 0, nxi - 1);
    let i1 = min(i0 + 1, nxi - 1);
    var fj = floor(y);
    let ty = y - fj;
    var j0 = i32(fj);
    j0 = clamp(j0, 0, nyf - 2);
    let j1 = min(j0 + 1, nyf - 1);
    let w00 = bar_w_face_read(i0, j0);
    let w10 = bar_w_face_read(i1, j0);
    let w01 = bar_w_face_read(i0, j1);
    let w11 = bar_w_face_read(i1, j1);
    return mix(mix(w00, w10, tx), mix(w01, w11, tx), ty);
}

fn bar_sample_w_bilinear_mac0(x: f32, y: f32) -> f32 {
    let nxi = bar_nxi();
    let nyf = bar_nxi() + 1;
    let ifloat = x - 0.5;
    var i0 = i32(floor(ifloat));
    let tx = ifloat - f32(i0);
    i0 = clamp(i0, 0, nxi - 1);
    let i1 = min(i0 + 1, nxi - 1);
    var fj = floor(y);
    let ty = y - fj;
    var j0 = i32(fj);
    j0 = clamp(j0, 0, nyf - 2);
    let j1 = min(j0 + 1, nyf - 1);
    let w00 = bar_w_mac0_at(i0, j0);
    let w10 = bar_w_mac0_at(i1, j0);
    let w01 = bar_w_mac0_at(i0, j1);
    let w11 = bar_w_mac0_at(i1, j1);
    return mix(mix(w00, w10, tx), mix(w01, w11, tx), ty);
}

fn bar_sample_mac_velocity_u_advect(x: f32, y: f32) -> vec2f {
    return vec2f(bar_sample_u_bilinear_mac0(x, y), bar_sample_w_bilinear(x, y));
}

fn bar_sample_mac_velocity_w_advect(x: f32, y: f32) -> vec2f {
    return vec2f(bar_sample_u_bilinear(x, y), bar_sample_w_bilinear_mac0(x, y));
}

fn bar_trace_semi_lag(pos: vec2f, v: vec2f, dt: f32) -> vec2f {
    let dx = sim.dx;
    let nx_f = f32(bar_nxi());
    let p = pos - v * (dt / dx);
    return vec2f(clamp(p.x, 0.0, nx_f), clamp(p.y, 0.0, nx_f));
}

fn bar_semi_lag_u_from(pos: vec2f, dt_sign: f32) -> f32 {
    let v = bar_sample_mac_velocity_u_advect(pos.x, pos.y);
    let pback = bar_trace_semi_lag(pos, v, sim.dt * dt_sign);
    return bar_sample_u_bilinear_mac0(pback.x, pback.y);
}

fn bar_semi_lag_w_from(pos: vec2f, dt_sign: f32) -> f32 {
    let v = bar_sample_mac_velocity_w_advect(pos.x, pos.y);
    let pback = bar_trace_semi_lag(pos, v, sim.dt * dt_sign);
    return bar_sample_w_bilinear_mac0(pback.x, pback.y);
}

fn bar_semi_lag_u_reverse_hat(pos: vec2f) -> f32 {
    let v = bar_sample_mac_velocity_u_advect(pos.x, pos.y);
    let pback = bar_trace_semi_lag(pos, v, -sim.dt);
    return bar_sample_u_bilinear(pback.x, pback.y);
}

fn bar_semi_lag_w_reverse_hat(pos: vec2f) -> f32 {
    let v = bar_sample_mac_velocity_w_advect(pos.x, pos.y);
    let pback = bar_trace_semi_lag(pos, v, -sim.dt);
    return bar_sample_w_bilinear(pback.x, pback.y);
}

fn bar_clamp_face_vel(v: f32) -> f32 {
    let vm = sim.vel_clamp_alpha * sim.dx / max(sim.dt, 1e-6);
    return clamp(v, -vm, vm);
}

@compute @workgroup_size(16, 16, 1)
fn bar_sync_u_faces(@builtin(global_invocation_id) id: vec3u) {
    let nx = bar_nxi();
    if (id.x > u32(nx) || id.y >= u32(nx)) { return; }
    let fi = i32(id.x);
    let jc = i32(id.y);
    // Periodic: face 0 and face n are the same seam (between cell n-1 and cell 0).
    // Zeroing them made wall BCs that fight the periodic Airy path and launch edge lattices.
    let i_right = select(0, fi, fi < nx);
    let i_left = wrapi(i_right - 1, nx);
    let hl = bar_h_at(i_left, jc);
    let hr = bar_h_at(i_right, jc);
    let ql = bar_at(i_left, jc).g;
    let qr = bar_at(i_right, jc).g;
    let ul = ql / max(hl, 1e-6);
    let ur = qr / max(hr, 1e-6);
    let u_face = 0.5 * (ul + ur);
    textureStore(bar_face_u, id.xy, vec4f(bar_clamp_face_vel(u_face)));
}

@compute @workgroup_size(16, 16, 1)
fn bar_sync_w_faces(@builtin(global_invocation_id) id: vec3u) {
    let nx = bar_nxi();
    if (id.x >= u32(nx) || id.y > u32(nx)) { return; }
    let ic = i32(id.x);
    let fj = i32(id.y);
    let j_up = select(0, fj, fj < nx);
    let j_dn = wrapi(j_up - 1, nx);
    let hd = bar_h_at(ic, j_dn);
    let hu = bar_h_at(ic, j_up);
    let qd = bar_at(ic, j_dn).b;
    let qu = bar_at(ic, j_up).b;
    let vd = qd / max(hd, 1e-6);
    let vu = qu / max(hu, 1e-6);
    let w_face = 0.5 * (vd + vu);
    textureStore(bar_face_w, id.xy, vec4f(bar_clamp_face_vel(w_face)));
}

@compute @workgroup_size(16, 16, 1)
fn bar_mac_u_copy(@builtin(global_invocation_id) id: vec3u) {
    let nx = bar_nxi();
    let sx = u32(nx + 1);
    let sy = u32(nx);
    if (id.x >= sx || id.y >= sy) { return; }
    let u = textureLoad(bar_face_u, id.xy).x;
    textureStore(bar_mac_u, id.xy, vec4f(u, 0.0, 0.0, 0.0));
}

@compute @workgroup_size(16, 16, 1)
fn bar_mac_u_sl_forward(@builtin(global_invocation_id) id: vec3u) {
    let nx = bar_nxi();
    let sx = u32(nx + 1);
    let sy = u32(nx);
    if (id.x >= sx || id.y >= sy) { return; }
    let fi = i32(id.x);
    let jc = i32(id.y);
    let pos = vec2f(f32(fi), f32(jc) + 0.5);
    let u_hat = bar_semi_lag_u_from(pos, 1.0);
    textureStore(bar_face_u, id.xy, vec4f(bar_clamp_face_vel(u_hat)));
}

@compute @workgroup_size(16, 16, 1)
fn bar_mac_u_sl_reverse(@builtin(global_invocation_id) id: vec3u) {
    let nx = bar_nxi();
    let sx = u32(nx + 1);
    let sy = u32(nx);
    if (id.x >= sx || id.y >= sy) { return; }
    let fi = i32(id.x);
    let jc = i32(id.y);
    let pos = vec2f(f32(fi), f32(jc) + 0.5);
    let u_tilde = bar_semi_lag_u_reverse_hat(pos);
    var mu = textureLoad(bar_mac_u, id.xy);
    mu.y = u_tilde;
    textureStore(bar_mac_u, id.xy, mu);
}

@compute @workgroup_size(16, 16, 1)
fn bar_mac_u_combine(@builtin(global_invocation_id) id: vec3u) {
    let nx = bar_nxi();
    let sx = u32(nx + 1);
    let sy = u32(nx);
    if (id.x >= sx || id.y >= sy) { return; }
    let mu = textureLoad(bar_mac_u, id.xy);
    let u_n = mu.x;
    let u_hat = textureLoad(bar_face_u, id.xy).x;
    let u_tilde = mu.y;
    var u_new = u_hat + 0.5 * (u_n - u_tilde);
    let min_u = min(u_n, u_hat);
    let max_u = max(u_n, u_hat);
    if (u_new < min_u - 1e-5 || u_new > max_u + 1e-5) { u_new = u_hat; }
    textureStore(bar_face_u, id.xy, vec4f(bar_clamp_face_vel(u_new)));
}

@compute @workgroup_size(16, 16, 1)
fn bar_mac_w_copy(@builtin(global_invocation_id) id: vec3u) {
    let nx = bar_nxi();
    let sx = u32(nx);
    let sy = u32(nx + 1);
    if (id.x >= sx || id.y >= sy) { return; }
    let w = textureLoad(bar_face_w, id.xy).x;
    textureStore(bar_mac_w, id.xy, vec4f(w, 0.0, 0.0, 0.0));
}

@compute @workgroup_size(16, 16, 1)
fn bar_mac_w_sl_forward(@builtin(global_invocation_id) id: vec3u) {
    let nx = bar_nxi();
    let sx = u32(nx);
    let sy = u32(nx + 1);
    if (id.x >= sx || id.y >= sy) { return; }
    let ic = i32(id.x);
    let fj = i32(id.y);
    let pos = vec2f(f32(ic) + 0.5, f32(fj));
    let w_hat = bar_semi_lag_w_from(pos, 1.0);
    textureStore(bar_face_w, id.xy, vec4f(bar_clamp_face_vel(w_hat)));
}

@compute @workgroup_size(16, 16, 1)
fn bar_mac_w_sl_reverse(@builtin(global_invocation_id) id: vec3u) {
    let nx = bar_nxi();
    let sx = u32(nx);
    let sy = u32(nx + 1);
    if (id.x >= sx || id.y >= sy) { return; }
    let ic = i32(id.x);
    let fj = i32(id.y);
    let pos = vec2f(f32(ic) + 0.5, f32(fj));
    let w_tilde = bar_semi_lag_w_reverse_hat(pos);
    var mw = textureLoad(bar_mac_w, id.xy);
    mw.y = w_tilde;
    textureStore(bar_mac_w, id.xy, mw);
}

@compute @workgroup_size(16, 16, 1)
fn bar_mac_w_combine(@builtin(global_invocation_id) id: vec3u) {
    let nx = bar_nxi();
    let sx = u32(nx);
    let sy = u32(nx + 1);
    if (id.x >= sx || id.y >= sy) { return; }
    let mw = textureLoad(bar_mac_w, id.xy);
    let w_n = mw.x;
    let w_hat = textureLoad(bar_face_w, id.xy).x;
    let w_tilde = mw.y;
    var w_new = w_hat + 0.5 * (w_n - w_tilde);
    let min_w = min(w_n, w_hat);
    let max_w = max(w_n, w_hat);
    if (w_new < min_w - 1e-5 || w_new > max_w + 1e-5) { w_new = w_hat; }
    textureStore(bar_face_w, id.xy, vec4f(bar_clamp_face_vel(w_new)));
}

fn bar_h_adj_cell(ic: i32, jc: i32) -> f32 {
    let g = sim.g;
    let dt = sim.dt;
    let dx = sim.dx;
    let beta = sim.h_avgmax_beta;
    let h_avgmax = beta * dx / (g * dt);
    let h_e = bar_h_at(ic + 1, jc);
    let h_w = bar_h_at(ic - 1, jc);
    let h_n = bar_h_at(ic, jc + 1);
    let h_s = bar_h_at(ic, jc - 1);
    let avg = 0.25 * (h_e + h_w + h_n + h_s);
    return max(0.0, avg - h_avgmax);
}

fn bar_upwind_h_flux(h_up: f32, h_dn: f32, u_face: f32, h_adj_up: f32, h_adj_dn: f32) -> f32 {
    let hu = select(h_dn - h_adj_dn, h_up - h_adj_up, u_face > 0.0);
    return u_face * max(0.0, hu);
}

@compute @workgroup_size(16, 16, 1)
fn bar_cmf10_integrate_height(@builtin(global_invocation_id) id: vec3u) {
    let n = sim.n;
    if (id.x >= n || id.y >= n) { return; }
    let i = i32(id.x);
    let j = i32(id.y);
    let dx = sim.dx;
    let dt = sim.dt;
    let uL = bar_u_face_read(i, j);
    let uR = bar_u_face_read(i + 1, j);
    let wB = bar_w_face_read(i, j);
    let wT = bar_w_face_read(i, j + 1);
    let aj = bar_h_adj_cell(i, j);
    let aj_l = bar_h_adj_cell(i - 1, j);
    let aj_r = bar_h_adj_cell(i + 1, j);
    let aj_b = bar_h_adj_cell(i, j - 1);
    let aj_t = bar_h_adj_cell(i, j + 1);
    let h_c = bar_h_at(i, j);
    let h_l = bar_h_at(i - 1, j);
    let h_r = bar_h_at(i + 1, j);
    let h_d = bar_h_at(i, j - 1);
    let h_u = bar_h_at(i, j + 1);
    let f_e = bar_upwind_h_flux(h_c, h_r, uR, aj, aj_r);
    let f_w = bar_upwind_h_flux(h_l, h_c, uL, aj_l, aj);
    let f_n = bar_upwind_h_flux(h_c, h_u, wT, aj, aj_t);
    let f_s = bar_upwind_h_flux(h_d, h_c, wB, aj_b, aj);
    let div = f_e - f_w + f_n - f_s;
    var db = textureLoad(d_bar, id.xy);
    db.x += -dt / dx * div;
    db.x = max(0.0, db.x);
    textureStore(d_bar, id.xy, db);
}

@compute @workgroup_size(16, 16, 1)
fn bar_cmf10_vel_u(@builtin(global_invocation_id) id: vec3u) {
    let nx = bar_nxi();
    let sx = u32(nx + 1);
    let sy = u32(nx);
    if (id.x >= sx || id.y >= sy) { return; }
    let fi = i32(id.x);
    let jc = i32(id.y);
    if (fi < 1 || fi > nx) { return; }
    let g = sim.g;
    let dx = sim.dx;
    let dt = sim.dt;
    let eta_l = bar_eta_at(fi - 1, jc);
    let eta_r = bar_eta_at(fi, jc);
    var u = textureLoad(bar_face_u, id.xy).x;
    u += (-g / dx * (eta_r - eta_l)) * dt;
    textureStore(bar_face_u, id.xy, vec4f(bar_clamp_face_vel(u)));
}

@compute @workgroup_size(16, 16, 1)
fn bar_cmf10_vel_w(@builtin(global_invocation_id) id: vec3u) {
    let nx = bar_nxi();
    let sx = u32(nx);
    let sy = u32(nx + 1);
    if (id.x >= sx || id.y >= sy) { return; }
    let ic = i32(id.x);
    let fj = i32(id.y);
    if (fj < 1 || fj > nx) { return; }
    let g = sim.g;
    let dx = sim.dx;
    let dt = sim.dt;
    let eta_d = bar_eta_at(ic, fj - 1);
    let eta_u = bar_eta_at(ic, fj);
    var wv = textureLoad(bar_face_w, id.xy).x;
    wv += (-g / dx * (eta_u - eta_d)) * dt;
    textureStore(bar_face_w, id.xy, vec4f(bar_clamp_face_vel(wv)));
}

@compute @workgroup_size(16, 16, 1)
fn bar_gather_cell_q(@builtin(global_invocation_id) id: vec3u) {
    let n = sim.n;
    if (id.x >= n || id.y >= n) { return; }
    let i = i32(id.x);
    let j = i32(id.y);
    let h = max(textureLoad(d_bar, id.xy).r, 0.0);
    let uL = bar_u_face_read(i, j);
    let uR = bar_u_face_read(i + 1, j);
    let wB = bar_w_face_read(i, j);
    let wT = bar_w_face_read(i, j + 1);
    let u_avg = 0.5 * (uL + uR);
    let v_avg = 0.5 * (wB + wT);
    var qx = h * u_avg;
    var qy = h * v_avg;
    let dx = sim.dx;
    let dt = sim.dt;
    let h_safe = max(h, 1e-3);
    let u_m = dx / (4.0 * max(dt, 1e-6));
    let ul = length(vec2f(qx / h_safe, qy / h_safe));
    if (ul > u_m) {
        let sc = u_m / max(ul, 1e-6);
        qx = (qx / h_safe) * sc * h_safe;
        qy = (qy / h_safe) * sc * h_safe;
    }
    textureStore(d_bar, id.xy, vec4(h, qx, qy, 0.0));
}

@compute @workgroup_size(16, 16, 1)
fn pack_h_t_to_a(@builtin(global_invocation_id) id: vec3u) {
    let n = sim.n;
    if (id.x >= n || id.y >= n) { return; }
    let t = textureLoad(d_tilde, id.xy);
    // Alg. 2: FFT the un-staggered average (h̃^{t−Δt/2} + h̃^{t+Δt/2}) / 2.
    let h_avg = 0.5 * (t.r + t.a);
    let z = vec4f(0.0, 0.0, 0.0, 0.0);
    textureStore(buffer_a_re, id.xy, vec4(h_avg, 0.0, 0.0, 0.0));
    textureStore(buffer_a_im, id.xy, z);
    // Next step's previous half-step is this pre-Airy decompose height.
    textureStore(d_tilde, id.xy, vec4(t.r, t.g, t.b, t.r));
}

@compute @workgroup_size(16, 16, 1)
fn copy_c_to_hspec(@builtin(global_invocation_id) id: vec3u) {
    let n = sim.n;
    if (id.x >= n || id.y >= n) { return; }
    let damp = spectral_damp(length(k_xy(id.xy)));
    var cr = textureLoad(buffer_c_re, id.xy);
    var ci = textureLoad(buffer_c_im, id.xy);
    cr.x *= damp;
    ci.x *= damp;
    textureStore(buffer_c_re, id.xy, cr);
    textureStore(buffer_c_im, id.xy, ci);
    textureStore(d_hspec_re, id.xy, cr);
    textureStore(d_hspec_im, id.xy, ci);
}

/// After `copy_c_to_hspec` + inverse FFT, write band-limited ĥ back into `tilde.r`.
/// Airy only updates q̃; latticed h̃ was still driving merge `div_check` and the next pack.
@compute @workgroup_size(16, 16, 1)
fn unpack_b_re_to_tilde_h(@builtin(global_invocation_id) id: vec3u) {
    let n = sim.n;
    if (id.x >= n || id.y >= n) { return; }
    let t = textureLoad(d_tilde, id.xy);
    var h = textureLoad(buffer_b_re, id.xy).x;
    if (!is_finite_f(h)) { h = 0.0; }
    textureStore(d_tilde, id.xy, vec4(h, t.g, t.b, t.a));
}

@compute @workgroup_size(16, 16, 1)
fn pack_qx_t_to_a(@builtin(global_invocation_id) id: vec3u) {
    let n = sim.n;
    if (id.x >= n || id.y >= n) { return; }
    let t = textureLoad(d_tilde, id.xy);
    let z = vec4f(0.0, 0.0, 0.0, 0.0);
    textureStore(buffer_a_re, id.xy, vec4(t.g, 0.0, 0.0, 0.0));
    textureStore(buffer_a_im, id.xy, z);
}

@compute @workgroup_size(16, 16, 1)
fn pack_qy_t_to_a(@builtin(global_invocation_id) id: vec3u) {
    let n = sim.n;
    if (id.x >= n || id.y >= n) { return; }
    let t = textureLoad(d_tilde, id.xy);
    let z = vec4f(0.0, 0.0, 0.0, 0.0);
    textureStore(buffer_a_re, id.xy, vec4(t.b, 0.0, 0.0, 0.0));
    textureStore(buffer_a_im, id.xy, z);
}

@compute @workgroup_size(16, 16, 1)
fn qspec_save_c_to_backup(@builtin(global_invocation_id) id: vec3u) {
    let n = sim.n;
    if (id.x >= n || id.y >= n) { return; }
    let damp = spectral_damp(length(k_xy(id.xy)));
    var cr = textureLoad(buffer_c_re, id.xy);
    var ci = textureLoad(buffer_c_im, id.xy);
    cr.x *= damp;
    ci.x *= damp;
    textureStore(buffer_c_re, id.xy, cr);
    textureStore(buffer_c_im, id.xy, ci);
    textureStore(d_qspec_backup, id.xy, vec4(cr.x, ci.x, 0.0, 0.0));
}

@compute @workgroup_size(16, 16, 1)
fn qspec_restore_backup_to_c(@builtin(global_invocation_id) id: vec3u) {
    let n = sim.n;
    if (id.x >= n || id.y >= n) { return; }
    let b = textureLoad(d_qspec_backup, id.xy);
    var cr = textureLoad(buffer_c_re, id.xy);
    var ci = textureLoad(buffer_c_im, id.xy);
    cr.x = b.r;
    ci.x = b.g;
    textureStore(buffer_c_re, id.xy, cr);
    textureStore(buffer_c_im, id.xy, ci);
}

@compute @workgroup_size(16, 16, 1)
fn airy_stack_clear_qx(@builtin(global_invocation_id) id: vec3u) {
    let n = sim.n;
    if (id.x >= n || id.y >= n) { return; }
    textureStore(d_airy_stack_qx, id.xy, vec4(0.0));
}

@compute @workgroup_size(16, 16, 1)
fn airy_stack_clear_qy(@builtin(global_invocation_id) id: vec3u) {
    let n = sim.n;
    if (id.x >= n || id.y >= n) { return; }
    textureStore(d_airy_stack_qy, id.xy, vec4(0.0));
}

@compute @workgroup_size(16, 16, 1)
fn airy_stack_write_qx_from_b(@builtin(global_invocation_id) id: vec3u) {
    let n = sim.n;
    if (id.x >= n || id.y >= n) { return; }
    var v = textureLoad(buffer_b_re, id.xy).x;
    if (!is_finite_f(v)) { v = 0.0; }
    let s = textureLoad(d_airy_stack_qx, id.xy);
    let ch = sim.airy_stack_channel;
    var o = s;
    switch ch {
        case 0u: { o.x = v; }
        case 1u: { o.y = v; }
        case 2u: { o.z = v; }
        default: { o.w = v; }
    }
    textureStore(d_airy_stack_qx, id.xy, o);
}

@compute @workgroup_size(16, 16, 1)
fn airy_stack_write_qy_from_b(@builtin(global_invocation_id) id: vec3u) {
    let n = sim.n;
    if (id.x >= n || id.y >= n) { return; }
    var v = textureLoad(buffer_b_re, id.xy).x;
    if (!is_finite_f(v)) { v = 0.0; }
    let s = textureLoad(d_airy_stack_qy, id.xy);
    let ch = sim.airy_stack_channel;
    var o = s;
    switch ch {
        case 0u: { o.x = v; }
        case 1u: { o.y = v; }
        case 2u: { o.z = v; }
        default: { o.w = v; }
    }
    textureStore(d_airy_stack_qy, id.xy, o);
}

fn lerp_depth_sample(h_bar: f32, d0: f32, d1: f32, d2: f32, d3: f32, v: vec4f) -> f32 {
    let h = max(h_bar, 1e-6);
    if (h <= d0) {
        return v.x;
    }
    if (h >= d3) {
        return v.w;
    }
    if (h <= d1) {
        let t = (h - d0) / max(d1 - d0, 1e-6);
        return mix(v.x, v.y, clamp(t, 0.0, 1.0));
    }
    if (h <= d2) {
        let t = (h - d1) / max(d2 - d1, 1e-6);
        return mix(v.y, v.z, clamp(t, 0.0, 1.0));
    }
    let t = (h - d2) / max(d3 - d2, 1e-6);
    return mix(v.z, v.w, clamp(t, 0.0, 1.0));
}

@compute @workgroup_size(16, 16, 1)
fn blend_airy_qx_to_tilde(@builtin(global_invocation_id) id: vec3u) {
    let n = sim.n;
    if (id.x >= n || id.y >= n) { return; }
    let hb = max(textureLoad(d_bar, id.xy).r, sim.h_bar_omega);
    let st = textureLoad(d_airy_stack_qx, id.xy);
    let t = textureLoad(d_tilde, id.xy);
    var qx_b = lerp_depth_sample(hb, sim.airy_depth_0, sim.airy_depth_1, sim.airy_depth_2, sim.airy_depth_3, st);
    if (!is_finite_f(qx_b)) { qx_b = 0.0; }
    textureStore(d_tilde, id.xy, vec4(t.r, qx_b, t.b, t.a));
}

@compute @workgroup_size(16, 16, 1)
fn blend_airy_qy_to_tilde(@builtin(global_invocation_id) id: vec3u) {
    let n = sim.n;
    if (id.x >= n || id.y >= n) { return; }
    let hb = max(textureLoad(d_bar, id.xy).r, sim.h_bar_omega);
    let st = textureLoad(d_airy_stack_qy, id.xy);
    let t = textureLoad(d_tilde, id.xy);
    var qy_b = lerp_depth_sample(hb, sim.airy_depth_0, sim.airy_depth_1, sim.airy_depth_2, sim.airy_depth_3, st);
    if (!is_finite_f(qy_b)) { qy_b = 0.0; }
    let qcl = clamp_q_cell(max(hb + t.r, 1e-3), t.g, qy_b);
    textureStore(d_tilde, id.xy, vec4(t.r, qcl.x, qcl.y, t.a));
}

/// FFT-aligned wavenumbers (same rule as `ewave_k_step` / README).
/// Stock forward FFT leaves DC at `(0,0)`, then positive bins, then wrapped negatives.
/// Do not use a centered `i - N/2` grid unless the spectrum was explicitly fftshifted.
fn k_xy(id: vec2u) -> vec2f {
    let d = 2.0 * PI / sim.tile_world;
    let n_f = f32(sim.n);
    let hf = 0.5 * n_f;
    let kx = select(
        (f32(id.x) - n_f) * d,
        f32(id.x) * d,
        f32(id.x) <= hf
    );
    let ky = select(
        (f32(id.y) - n_f) * d,
        f32(id.y) * d,
        f32(id.y) <= hf
    );
    return vec2f(kx, ky);
}

/// Wavenumber used in `i k` derivatives. Zero the even-N Nyquist axis component so the
/// real-valued Nyquist bin cannot drive odd/even lattice forcing through ∂/∂x or ∂/∂y.
fn k_xy_deriv(id: vec2u) -> vec2f {
    var k = k_xy(id);
    let n_half = sim.n / 2u;
    if (sim.n >= 2u && id.x == n_half) { k.x = 0.0; }
    if (sim.n >= 2u && id.y == n_half) { k.y = 0.0; }
    return k;
}

fn spectral_damp(klen: f32) -> f32 {
    let k_nyq = PI / max(sim.dx, 1e-6);
    let kn = klen / max(k_nyq, 1e-6);
    // Paper Fig. 6 claims β to Nyquist, but Airy still puts energy into kn≳0.5.
    // Soft roll-off keeps short wakes without Nyquist froth.
    if (kn > 0.5) {
        return 0.0;
    }
    let t = clamp((kn - 0.28) / 0.22, 0.0, 1.0);
    return exp(-8.0 * t * t);
}

fn beta_num(k: f32, dx: f32) -> f32 {
    if (k < 1e-10) { return 0.0; }
    let s = sin(k * dx * 0.5);
    // Paper Eq. 27: β = sqrt(2k/Δx) * sqrt(sin(k Δx/2)). Units of wavenumber.
    return sqrt(max((2.0 * k / max(dx, 1e-6)) * s, 0.0));
}

fn omega_disp(g: f32, k: f32, hbar: f32, dx: f32) -> f32 {
    if (k < 1e-10) { return 0.0; }
    let b = beta_num(k, dx);
    let raw = sqrt(max(g * k * tanh(k * hbar), 0.0));
    // Eq. 27 β is a wavenumber (≈ k at long waves). The dimensionless factor is β/k, so
    // ω_corr = ω_phys / (β/k) = ω_phys * k / β. Using ω_phys/β fed phase speed into cos/sin
    // and made (ω/k²) explode by ~1/k², which NaNs the Airy IFFT within a few steps.
    let b_safe = max(b, 1e-6);
    return raw * (k / b_safe);
}

// Half-cell shift e^{-i k·Δ/2} on ĥ for x (qx) or y (qy) derivative (paper Sec. 4.3).
fn h_phase_shift_x(hre: f32, him: f32, kx: f32) -> vec2f {
    let th = kx * sim.dx * 0.5;
    let ct = cos(th);
    let st = sin(th);
    return vec2f(hre * ct + him * st, him * ct - hre * st);
}

fn h_phase_shift_y(hre: f32, him: f32, ky: f32) -> vec2f {
    let th = ky * sim.dx * 0.5;
    let ct = cos(th);
    let st = sin(th);
    return vec2f(hre * ct + him * st, him * ct - hre * st);
}

@compute @workgroup_size(16, 16, 1)
fn hybrid_k_qx(@builtin(global_invocation_id) id: vec3u) {
    let n = sim.n;
    if (id.x >= n || id.y >= n) { return; }
    let k2 = k_xy(id.xy);
    let kd = k_xy_deriv(id.xy);
    let klen = length(k2);
    var hbar = max(textureLoad(d_bar, id.xy).r, sim.h_bar_omega);
    if ((sim.spectral_flags & SPECTRAL_FIXED_DEPTH) != 0u) {
        hbar = max(sim.spectral_fixed_depth, sim.h_bar_omega);
    }
    let w = omega_disp(sim.g, klen, hbar, sim.dx);
    let dt = sim.dt;
    let c = cos(w * dt);
    let s = sin(w * dt);
    var qre = textureLoad(buffer_c_re, id.xy);
    var qim = textureLoad(buffer_c_im, id.xy);
    let hre0 = textureLoad(d_hspec_re, id.xy).x;
    let him0 = textureLoad(d_hspec_im, id.xy).x;
    let k2_safe = max(klen * klen, 1e-12);
    let damp = spectral_damp(klen);
    if (klen < 1e-8) {
        var out_re = qre;
        var out_im = qim;
        out_re.x = qre.x * damp;
        out_im.x = qim.x * damp;
        textureStore(buffer_c_re, id.xy, out_re);
        textureStore(buffer_c_im, id.xy, out_im);
        return;
    }
    let kx = kd.x;
    let hp = h_phase_shift_x(hre0, him0, kx);
    let hre = hp.x;
    let him = hp.y;
    let sc = s * (w / k2_safe);
    var oqx_re = (c * qre.x + sc * kx * him) * damp;
    var oqx_im = (c * qim.x - sc * kx * hre) * damp;
    if (!is_finite_f(oqx_re)) { oqx_re = 0.0; }
    if (!is_finite_f(oqx_im)) { oqx_im = 0.0; }
    var out_re = qre;
    out_re.x = oqx_re;
    var out_im = qim;
    out_im.x = oqx_im;
    textureStore(buffer_c_re, id.xy, out_re);
    textureStore(buffer_c_im, id.xy, out_im);
}

@compute @workgroup_size(16, 16, 1)
fn hybrid_k_qy(@builtin(global_invocation_id) id: vec3u) {
    let n = sim.n;
    if (id.x >= n || id.y >= n) { return; }
    let k2 = k_xy(id.xy);
    let kd = k_xy_deriv(id.xy);
    let klen = length(k2);
    var hbar = max(textureLoad(d_bar, id.xy).r, sim.h_bar_omega);
    if ((sim.spectral_flags & SPECTRAL_FIXED_DEPTH) != 0u) {
        hbar = max(sim.spectral_fixed_depth, sim.h_bar_omega);
    }
    let w = omega_disp(sim.g, klen, hbar, sim.dx);
    let dt = sim.dt;
    let c = cos(w * dt);
    let s = sin(w * dt);
    var qre = textureLoad(buffer_c_re, id.xy);
    var qim = textureLoad(buffer_c_im, id.xy);
    let hre0 = textureLoad(d_hspec_re, id.xy).x;
    let him0 = textureLoad(d_hspec_im, id.xy).x;
    let k2_safe = max(klen * klen, 1e-12);
    let damp = spectral_damp(klen);
    if (klen < 1e-8) {
        var out_re = qre;
        var out_im = qim;
        out_re.x = qre.x * damp;
        out_im.x = qim.x * damp;
        textureStore(buffer_c_re, id.xy, out_re);
        textureStore(buffer_c_im, id.xy, out_im);
        return;
    }
    let ky = kd.y;
    let hp = h_phase_shift_y(hre0, him0, ky);
    let hre = hp.x;
    let him = hp.y;
    let sc = s * (w / k2_safe);
    var oqy_re = (c * qre.x + sc * ky * him) * damp;
    var oqy_im = (c * qim.x - sc * ky * hre) * damp;
    if (!is_finite_f(oqy_re)) { oqy_re = 0.0; }
    if (!is_finite_f(oqy_im)) { oqy_im = 0.0; }
    var out_re = qre;
    out_re.x = oqy_re;
    var out_im = qim;
    out_im.x = oqy_im;
    textureStore(buffer_c_re, id.xy, out_re);
    textureStore(buffer_c_im, id.xy, out_im);
}

fn scratch_at(ix: i32, iy: i32, n: i32) -> vec4f {
    return textureLoad(d_scratch, vec2u(u32(wrapi(ix, n)), u32(wrapi(iy, n))));
}

fn catmull_rom_v4(p0: vec4f, p1: vec4f, p2: vec4f, p3: vec4f, t: f32) -> vec4f {
    let t2 = t * t;
    let t3 = t2 * t;
    return 0.5 * ((2.0 * p1)
        + (-p0 + p2) * t
        + (2.0 * p0 - 5.0 * p1 + 4.0 * p2 - p3) * t2
        + (-p0 + 3.0 * p1 - 3.0 * p2 + p3) * t3);
}

// Paper Sec. 4.4: cubic SL (Fedkiw et al.) with clamp to the four nearest samples.
fn cubic_sl_v4_from_scratch(p: vec2f, n: u32) -> vec4f {
    let ni = i32(n);
    let nf = f32(n);
    let x = (p.x % nf + nf) % nf;
    let y = (p.y % nf + nf) % nf;
    let i0 = i32(floor(x));
    let j0 = i32(floor(y));
    let tx = x - f32(i0);
    let ty = y - f32(j0);
    let r0 = catmull_rom_v4(
        scratch_at(i0 - 1, j0 - 1, ni), scratch_at(i0, j0 - 1, ni),
        scratch_at(i0 + 1, j0 - 1, ni), scratch_at(i0 + 2, j0 - 1, ni), tx);
    let r1 = catmull_rom_v4(
        scratch_at(i0 - 1, j0, ni), scratch_at(i0, j0, ni),
        scratch_at(i0 + 1, j0, ni), scratch_at(i0 + 2, j0, ni), tx);
    let r2 = catmull_rom_v4(
        scratch_at(i0 - 1, j0 + 1, ni), scratch_at(i0, j0 + 1, ni),
        scratch_at(i0 + 1, j0 + 1, ni), scratch_at(i0 + 2, j0 + 1, ni), tx);
    let r3 = catmull_rom_v4(
        scratch_at(i0 - 1, j0 + 2, ni), scratch_at(i0, j0 + 2, ni),
        scratch_at(i0 + 1, j0 + 2, ni), scratch_at(i0 + 2, j0 + 2, ni), tx);
    let v = catmull_rom_v4(r0, r1, r2, r3, ty);
    let v00 = scratch_at(i0, j0, ni);
    let v10 = scratch_at(i0 + 1, j0, ni);
    let v01 = scratch_at(i0, j0 + 1, ni);
    let v11 = scratch_at(i0 + 1, j0 + 1, ni);
    let vmin = min(min(v00, v10), min(v01, v11));
    let vmax = max(max(v00, v10), max(v01, v11));
    return clamp(v, vmin, vmax);
}

fn bar_cell_vel(ix: i32, iy: i32) -> vec2f {
    let u_w = bar_u_face_read(ix, iy);
    let u_e = bar_u_face_read(ix + 1, iy);
    let v_s = bar_w_face_read(ix, iy);
    let v_n = bar_w_face_read(ix, iy + 1);
    return vec2f(0.5 * (u_w + u_e), 0.5 * (v_s + v_n));
}

fn bar_face_div(ix: i32, iy: i32) -> f32 {
    let dx = sim.dx;
    let u_w = bar_u_face_read(ix, iy);
    let u_e = bar_u_face_read(ix + 1, iy);
    let v_s = bar_w_face_read(ix, iy);
    let v_n = bar_w_face_read(ix, iy + 1);
    return (u_e - u_w) / dx + (v_n - v_s) / dx;
}

fn growth_fac_from_div(div: f32) -> f32 {
    var G = -div;
    let gm = -sim.gamma_surf * div;
    G = min(G, gm);
    G = clamp(G, -8.0, 8.0);
    return exp(G * sim.dt);
}

fn tilde_h_at(ix: i32, iy: i32, n: i32) -> f32 {
    return textureLoad(d_tilde, vec2u(u32(wrapi(ix, n)), u32(wrapi(iy, n)))).r;
}

fn catmull_rom_f(p0: f32, p1: f32, p2: f32, p3: f32, t: f32) -> f32 {
    let t2 = t * t;
    let t3 = t2 * t;
    return 0.5 * ((2.0 * p1)
        + (-p0 + p2) * t
        + (2.0 * p0 - 5.0 * p1 + 4.0 * p2 - p3) * t2
        + (-p0 + 3.0 * p1 - 3.0 * p2 + p3) * t3);
}

/// Periodic cubic SL of transported h̃ (scalar), clamp to four nearest cells.
fn cubic_sl_h_tilde(p: vec2f, n: u32) -> f32 {
    let ni = i32(n);
    let nf = f32(n);
    let x = (p.x % nf + nf) % nf;
    let y = (p.y % nf + nf) % nf;
    let i0 = i32(floor(x));
    let j0 = i32(floor(y));
    let tx = x - f32(i0);
    let ty = y - f32(j0);
    let r0 = catmull_rom_f(
        tilde_h_at(i0 - 1, j0 - 1, ni), tilde_h_at(i0, j0 - 1, ni),
        tilde_h_at(i0 + 1, j0 - 1, ni), tilde_h_at(i0 + 2, j0 - 1, ni), tx);
    let r1 = catmull_rom_f(
        tilde_h_at(i0 - 1, j0, ni), tilde_h_at(i0, j0, ni),
        tilde_h_at(i0 + 1, j0, ni), tilde_h_at(i0 + 2, j0, ni), tx);
    let r2 = catmull_rom_f(
        tilde_h_at(i0 - 1, j0 + 1, ni), tilde_h_at(i0, j0 + 1, ni),
        tilde_h_at(i0 + 1, j0 + 1, ni), tilde_h_at(i0 + 2, j0 + 1, ni), tx);
    let r3 = catmull_rom_f(
        tilde_h_at(i0 - 1, j0 + 2, ni), tilde_h_at(i0, j0 + 2, ni),
        tilde_h_at(i0 + 1, j0 + 2, ni), tilde_h_at(i0 + 2, j0 + 2, ni), tx);
    let v = catmull_rom_f(r0, r1, r2, r3, ty);
    let v00 = tilde_h_at(i0, j0, ni);
    let v10 = tilde_h_at(i0 + 1, j0, ni);
    let v01 = tilde_h_at(i0, j0 + 1, ni);
    let v11 = tilde_h_at(i0 + 1, j0 + 1, ni);
    let vmin = min(min(v00, v10), min(v01, v11));
    let vmax = max(max(v00, v10), max(v01, v11));
    return clamp(v, vmin, vmax);
}

// Alg. 3–4: grow with face divergence (q at midpoint ū, h at end ū), then SL.
@compute @workgroup_size(16, 16, 1)
fn transport_copy_tilde_to_scratch(@builtin(global_invocation_id) id: vec3u) {
    let n = sim.n;
    if (id.x >= n || id.y >= n) { return; }
    let ix = i32(id.x);
    let iy = i32(id.y);
    let ni = i32(n);
    let b = textureLoad(d_bar, id.xy);

    let fac_h = growth_fac_from_div(bar_face_div(ix, iy));

    // Midpoint face velocities ≈ 0.5 * (previous cell-edge estimate + current face).
    let upe = textureLoad(bar_vel_prev, id.xy).xy;
    let upr = textureLoad(bar_vel_prev, vec2u(u32(wrapi(ix + 1, ni)), u32(iy))).xy;
    let upu = textureLoad(bar_vel_prev, vec2u(u32(ix), u32(wrapi(iy + 1, ni)))).xy;
    let upl = textureLoad(bar_vel_prev, vec2u(u32(wrapi(ix - 1, ni)), u32(iy))).xy;
    let upd = textureLoad(bar_vel_prev, vec2u(u32(ix), u32(wrapi(iy - 1, ni)))).xy;
    let u_e = 0.5 * (0.5 * (upe.x + upr.x) + bar_u_face_read(ix + 1, iy));
    let u_w = 0.5 * (0.5 * (upl.x + upe.x) + bar_u_face_read(ix, iy));
    let v_n = 0.5 * (0.5 * (upe.y + upu.y) + bar_w_face_read(ix, iy + 1));
    let v_s = 0.5 * (0.5 * (upd.y + upe.y) + bar_w_face_read(ix, iy));
    let div_mid = (u_e - u_w) / sim.dx + (v_n - v_s) / sim.dx;
    let fac_q = growth_fac_from_div(div_mid);

    let t = textureLoad(d_tilde, id.xy);
    var hr = t.r * fac_h;
    var qx = t.g * fac_q;
    var qy = t.b * fac_q;
    if (!is_finite_f(hr)) { hr = 0.0; }
    if (!is_finite_f(qx)) { qx = 0.0; }
    if (!is_finite_f(qy)) { qy = 0.0; }
    let qcl = clamp_q_cell(max(hr + b.r, 0.05), qx, qy);
    textureStore(d_scratch, id.xy, vec4(hr, qcl.x, qcl.y, 0.0));
}

@compute @workgroup_size(16, 16, 1)
fn transport_advect_tilde(@builtin(global_invocation_id) id: vec3u) {
    let n = sim.n;
    if (id.x >= n || id.y >= n) { return; }
    let ix = i32(id.x);
    let iy = i32(id.y);
    let b = textureLoad(d_bar, id.xy);
    let u_end = bar_cell_vel(ix, iy);
    let u_prev = textureLoad(bar_vel_prev, id.xy).xy;
    let u_mid = 0.5 * (u_prev + u_end);
    let dx = sim.dx;
    let inv = sim.dt / max(dx, 1e-6);
    let p_q = vec2f(f32(id.x), f32(id.y)) - u_mid * inv;
    let p_h = vec2f(f32(id.x), f32(id.y)) - u_end * inv;
    let t_q = cubic_sl_v4_from_scratch(p_q, n);
    let t_h = cubic_sl_v4_from_scratch(p_h, n);
    var hr = t_h.r;
    var qx = t_q.g;
    var qy = t_q.b;
    if (!is_finite_f(hr)) { hr = 0.0; }
    if (!is_finite_f(qx)) { qx = 0.0; }
    if (!is_finite_f(qy)) { qy = 0.0; }
    let prev_a = textureLoad(d_tilde, id.xy).a;
    let qcl = clamp_q_cell(max(b.r + hr, 1e-3), qx, qy);
    textureStore(d_tilde, id.xy, vec4(hr, qcl.x, qcl.y, prev_a));
}

/// Cache cell-centered ū after the bulk step for next frame's Alg. 3 midpoint.
@compute @workgroup_size(16, 16, 1)
fn store_bar_vel_prev(@builtin(global_invocation_id) id: vec3u) {
    let n = sim.n;
    if (id.x >= n || id.y >= n) { return; }
    let uv = bar_cell_vel(i32(id.x), i32(id.y));
    textureStore(bar_vel_prev, id.xy, vec4(uv.x, uv.y, 0.0, 0.0));
}

// Eq. 17 with staggered finite-volume divergence (paper Sec. 4.5 / Appendix B).
// q̌ from half-step SL of transported h̃ onto faces (paper §4.5), not collocated h̃ū.
@compute @workgroup_size(16, 16, 1)
fn merge_to_state(@builtin(global_invocation_id) id: vec3u) {
    let n = sim.n;
    if (id.x >= n || id.y >= n) { return; }
    let ix = i32(id.x);
    let iy = i32(id.y);
    let s0 = s_at(ix, iy);
    let b = textureLoad(d_bar, id.xy);
    let t = textureLoad(d_tilde, id.xy);
    let bl = bar_at(ix - 1, iy);
    let bd = bar_at(ix, iy - 1);
    let tl = tilde_at(ix - 1, iy);
    let td = tilde_at(ix, iy - 1);
    // Cell q as +x/+y face flux (matches Airy half-cell shift in Sec. 4.3). Periodic wrap.
    let qe = b.g + t.g;
    let qw = bl.g + tl.g;
    let qn = b.b + t.b;
    let qs = bd.b + td.b;
    let dx = sim.dx;
    let divq = (qe - qw) / dx + (qn - qs) / dx;

    // Paper §4.5: half-step SL of h̃ onto +x/+y faces, then q̌ = h̃ ū.
    // West/south faces reuse the east/north flux of the left/down neighbor.
    let dt_half = 0.5 * sim.dt;
    let inv = dt_half / max(dx, 1e-6);
    let u_e = bar_u_face_read(ix + 1, iy);
    let v_e = 0.5 * (bar_w_face_read(ix, iy + 1) + bar_w_face_read(ix + 1, iy + 1));
    let ht_e = cubic_sl_h_tilde(
        vec2f(f32(ix) + 0.5 - u_e * inv, f32(iy) - v_e * inv),
        n,
    );
    let qxe = ht_e * u_e;

    let u_e_l = bar_u_face_read(ix, iy);
    let v_e_l = 0.5 * (bar_w_face_read(ix - 1, iy + 1) + bar_w_face_read(ix, iy + 1));
    let ht_e_l = cubic_sl_h_tilde(
        vec2f(f32(ix) - 0.5 - u_e_l * inv, f32(iy) - v_e_l * inv),
        n,
    );
    let qxw = ht_e_l * u_e_l;

    let v_n = bar_w_face_read(ix, iy + 1);
    let u_n = 0.5 * (bar_u_face_read(ix + 1, iy) + bar_u_face_read(ix + 1, iy + 1));
    let ht_n = cubic_sl_h_tilde(
        vec2f(f32(ix) - u_n * inv, f32(iy) + 0.5 - v_n * inv),
        n,
    );
    let qyn = ht_n * v_n;

    let v_n_d = bar_w_face_read(ix, iy);
    let u_n_d = 0.5 * (bar_u_face_read(ix + 1, iy - 1) + bar_u_face_read(ix + 1, iy));
    let ht_n_d = cubic_sl_h_tilde(
        vec2f(f32(ix) - u_n_d * inv, f32(iy) - 0.5 - v_n_d * inv),
        n,
    );
    let qys = ht_n_d * v_n_d;

    let div_check = (qxe - qxw) / dx + (qyn - qys) / dx;
    let div_total = divq + div_check;
    var h1 = s0.r - sim.dt * div_total;
    if (!is_finite_f(h1)) {
        h1 = select(4.0, s0.r, is_finite_f(s0.r));
    }
    h1 = max(h1, 0.0);
    var qx1 = qe;
    var qy1 = qn;
    if (!is_finite_f(qx1) || !is_finite_f(qy1)) {
        qx1 = 0.0;
        qy1 = 0.0;
    }
    let qcl = clamp_q_cell(h1, qx1, qy1);
    textureStore(d_state, id.xy, vec4(h1, qcl.x, qcl.y, 0.0));
}

// --- Post-merge spectral damp of total η and q (matches NumPy damp_state_fields).
// Airy damps h̃ only. A compact IC can leave a static high-k spike in total h; this
// clears it. Soft cutoff sits above physical ripple bands.

@compute @workgroup_size(16, 16, 1)
fn pack_state_eta_to_a(@builtin(global_invocation_id) id: vec3u) {
    let n = sim.n;
    if (id.x >= n || id.y >= n) { return; }
    let h = max(textureLoad(d_state, id.xy).r, 0.0);
    let eta = b_at(i32(id.x), i32(id.y)) + h;
    let z = vec4f(0.0, 0.0, 0.0, 0.0);
    textureStore(buffer_a_re, id.xy, vec4(eta, 0.0, 0.0, 0.0));
    textureStore(buffer_a_im, id.xy, z);
}

@compute @workgroup_size(16, 16, 1)
fn spectral_damp_c(@builtin(global_invocation_id) id: vec3u) {
    let n = sim.n;
    if (id.x >= n || id.y >= n) { return; }
    let damp = spectral_damp(length(k_xy(id.xy)));
    var cr = textureLoad(buffer_c_re, id.xy);
    var ci = textureLoad(buffer_c_im, id.xy);
    cr.x *= damp;
    ci.x *= damp;
    textureStore(buffer_c_re, id.xy, cr);
    textureStore(buffer_c_im, id.xy, ci);
}

@compute @workgroup_size(16, 16, 1)
fn unpack_b_to_state_h(@builtin(global_invocation_id) id: vec3u) {
    let n = sim.n;
    if (id.x >= n || id.y >= n) { return; }
    let s = textureLoad(d_state, id.xy);
    var eta = textureLoad(buffer_b_re, id.xy).x;
    if (!is_finite_f(eta)) {
        eta = b_at(i32(id.x), i32(id.y)) + max(s.r, 0.0);
    }
    let h = max(eta - b_at(i32(id.x), i32(id.y)), 0.0);
    textureStore(d_state, id.xy, vec4(h, s.g, s.b, 0.0));
}

@compute @workgroup_size(16, 16, 1)
fn pack_state_qx_to_a(@builtin(global_invocation_id) id: vec3u) {
    let n = sim.n;
    if (id.x >= n || id.y >= n) { return; }
    let s = textureLoad(d_state, id.xy);
    let z = vec4f(0.0, 0.0, 0.0, 0.0);
    textureStore(buffer_a_re, id.xy, vec4(s.g, 0.0, 0.0, 0.0));
    textureStore(buffer_a_im, id.xy, z);
}

@compute @workgroup_size(16, 16, 1)
fn unpack_b_to_state_qx(@builtin(global_invocation_id) id: vec3u) {
    let n = sim.n;
    if (id.x >= n || id.y >= n) { return; }
    let s = textureLoad(d_state, id.xy);
    var qx = textureLoad(buffer_b_re, id.xy).x;
    if (!is_finite_f(qx)) { qx = 0.0; }
    textureStore(d_state, id.xy, vec4(s.r, qx, s.b, 0.0));
}

@compute @workgroup_size(16, 16, 1)
fn pack_state_qy_to_a(@builtin(global_invocation_id) id: vec3u) {
    let n = sim.n;
    if (id.x >= n || id.y >= n) { return; }
    let s = textureLoad(d_state, id.xy);
    let z = vec4f(0.0, 0.0, 0.0, 0.0);
    textureStore(buffer_a_re, id.xy, vec4(s.b, 0.0, 0.0, 0.0));
    textureStore(buffer_a_im, id.xy, z);
}

@compute @workgroup_size(16, 16, 1)
fn unpack_b_to_state_qy_clamp(@builtin(global_invocation_id) id: vec3u) {
    let n = sim.n;
    if (id.x >= n || id.y >= n) { return; }
    let s = textureLoad(d_state, id.xy);
    var qy = textureLoad(buffer_b_re, id.xy).x;
    if (!is_finite_f(qy)) { qy = 0.0; }
    let qcl = clamp_q_cell(max(s.r, 0.0), s.g, qy);
    textureStore(d_state, id.xy, vec4(s.r, qcl.x, qcl.y, 0.0));
}

@compute @workgroup_size(16, 16, 1)
fn init_basin(@builtin(global_invocation_id) id: vec3u) {
    let n = sim.n;
    if (id.x >= n || id.y >= n) { return; }
    // Flat bed, constant rest depth. Interaction (brush / Space) seeds waves.
    let bed = -4.0;
    let h0 = 4.0;
    textureStore(d_bed, id.xy, vec4(bed, 0.0, 0.0, 0.0));
    textureStore(d_state, id.xy, vec4(h0, 0.0, 0.0, 0.0));
}

fn point_to_segment_distance(p: vec2f, s0: vec2f, s1: vec2f) -> f32 {
    if (all(s0 == s1)) { return length(p - s0); }
    let s = s1 - s0;
    let d = p - s0;
    let t = clamp(dot(d, s) / max(dot(s, s), 1e-8), 0.0, 1.0);
    return length(d - s * t);
}

/// Soft height splash on `d_state`. Height only here. Tangential wake flux goes
/// into the surface field via `brush_tilde_wake` after decompose.
@compute @workgroup_size(16, 16, 1)
fn brush_flow_impulse(@builtin(global_invocation_id) id: vec3u) {
    let n = sim.n;
    if (id.x >= n || id.y >= n || sim.brush_on == 0u) { return; }
    let position = vec2f(f32(id.x), f32(id.y));
    let a = vec2f(sim.pointer_ox, sim.pointer_oy);
    let b = vec2f(sim.pointer_x, sim.pointer_y);
    let dist = point_to_segment_distance(position, a, b);
    let radius = max(sim.brush_radius, 1.0);
    if (dist >= radius) { return; }
    let t = clamp(1.0 - dist / radius, 0.0, 1.0);
    let falloff = t * t * (3.0 - 2.0 * t);
    let stroke_len = length(b - a);
    let motion = smoothstep(0.5, 2.5, stroke_len);
    let w = falloff * sim.brush_strength * (0.2 + 0.8 * motion);
    var s = textureLoad(d_state, id.xy);
    s.r = max(s.r, 0.05) + 0.55 * w;
    textureStore(d_state, id.xy, s);
}

/// Tangential wake flux into the surface-wave field only (paper Sec. 4.6).
/// Runs after `decompose_split` so the bulk staggered solver never sees it.
@compute @workgroup_size(16, 16, 1)
fn brush_tilde_wake(@builtin(global_invocation_id) id: vec3u) {
    let n = sim.n;
    if (id.x >= n || id.y >= n || sim.brush_on == 0u) { return; }
    let position = vec2f(f32(id.x), f32(id.y));
    let a = vec2f(sim.pointer_ox, sim.pointer_oy);
    let b = vec2f(sim.pointer_x, sim.pointer_y);
    let stroke = b - a;
    let stroke_len = length(stroke);
    if (stroke_len < 2.5) { return; }
    let dist = point_to_segment_distance(position, a, b);
    let radius = max(sim.brush_radius, 1.0);
    if (dist >= radius) { return; }
    let t = clamp(1.0 - dist / radius, 0.0, 1.0);
    let falloff = t * t * (3.0 - 2.0 * t);
    let tangent = stroke / stroke_len;
    let w = falloff * sim.brush_strength;
    var td = textureLoad(d_tilde, id.xy);
    let h_ref = max(textureLoad(d_state, id.xy).r, 0.05);
    let u_along = 0.35 * w;
    td.g += h_ref * u_along * tangent.x;
    td.b += h_ref * u_along * tangent.y;
    textureStore(d_tilde, id.xy, vec4(td.r, td.g, td.b, td.a));
}
